#	BSDI Makefile,v 2.2 1995/07/21 22:14:40 bostic Exp

.include "../Makefile.defs"

LIB=	driver
SRCS=	input.cc printer.cc
NOPROFILE=noprofile
NOMAN=	noman

install tags:

.include "../Makefile.common"
.include <bsd.lib.mk>

.SUFFIXES: .cc
