/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "nlm_prot.h"
#pragma ident	"@(#)nlm_prot.x	1.5	94/02/01 SMI"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

nlm_testres *
nlm_test_1(nlm_testargs *argp, CLIENT *clnt)
{
	static nlm_testres clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLM_TEST,
		(xdrproc_t) xdr_nlm_testargs, (caddr_t) argp,
		(xdrproc_t) xdr_nlm_testres, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

nlm_res *
nlm_lock_1(nlm_lockargs *argp, CLIENT *clnt)
{
	static nlm_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLM_LOCK,
		(xdrproc_t) xdr_nlm_lockargs, (caddr_t) argp,
		(xdrproc_t) xdr_nlm_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

nlm_res *
nlm_cancel_1(nlm_cancargs *argp, CLIENT *clnt)
{
	static nlm_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLM_CANCEL,
		(xdrproc_t) xdr_nlm_cancargs, (caddr_t) argp,
		(xdrproc_t) xdr_nlm_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

nlm_res *
nlm_unlock_1(nlm_unlockargs *argp, CLIENT *clnt)
{
	static nlm_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLM_UNLOCK,
		(xdrproc_t) xdr_nlm_unlockargs, (caddr_t) argp,
		(xdrproc_t) xdr_nlm_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

nlm_res *
nlm_granted_1(nlm_testargs *argp, CLIENT *clnt)
{
	static nlm_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLM_GRANTED,
		(xdrproc_t) xdr_nlm_testargs, (caddr_t) argp,
		(xdrproc_t) xdr_nlm_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

void *
nlm_test_msg_1(nlm_testargs *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLM_TEST_MSG,
		(xdrproc_t) xdr_nlm_testargs, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

void *
nlm_lock_msg_1(nlm_lockargs *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLM_LOCK_MSG,
		(xdrproc_t) xdr_nlm_lockargs, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

void *
nlm_cancel_msg_1(nlm_cancargs *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLM_CANCEL_MSG,
		(xdrproc_t) xdr_nlm_cancargs, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

void *
nlm_unlock_msg_1(nlm_unlockargs *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLM_UNLOCK_MSG,
		(xdrproc_t) xdr_nlm_unlockargs, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

void *
nlm_granted_msg_1(nlm_testargs *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLM_GRANTED_MSG,
		(xdrproc_t) xdr_nlm_testargs, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

void *
nlm_test_res_1(nlm_testres *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLM_TEST_RES,
		(xdrproc_t) xdr_nlm_testres, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

void *
nlm_lock_res_1(nlm_res *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLM_LOCK_RES,
		(xdrproc_t) xdr_nlm_res, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

void *
nlm_cancel_res_1(nlm_res *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLM_CANCEL_RES,
		(xdrproc_t) xdr_nlm_res, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

void *
nlm_unlock_res_1(nlm_res *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLM_UNLOCK_RES,
		(xdrproc_t) xdr_nlm_res, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

void *
nlm_granted_res_1(nlm_res *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLM_GRANTED_RES,
		(xdrproc_t) xdr_nlm_res, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

void *
nlm_nsm_callback_1(status *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLM_NSM_CALLBACK,
		(xdrproc_t) xdr_status, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

nlm_shareres *
nlm_share_3(nlm_shareargs *argp, CLIENT *clnt)
{
	static nlm_shareres clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLM_SHARE,
		(xdrproc_t) xdr_nlm_shareargs, (caddr_t) argp,
		(xdrproc_t) xdr_nlm_shareres, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

nlm_shareres *
nlm_unshare_3(nlm_shareargs *argp, CLIENT *clnt)
{
	static nlm_shareres clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLM_UNSHARE,
		(xdrproc_t) xdr_nlm_shareargs, (caddr_t) argp,
		(xdrproc_t) xdr_nlm_shareres, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

nlm_res *
nlm_nm_lock_3(nlm_lockargs *argp, CLIENT *clnt)
{
	static nlm_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLM_NM_LOCK,
		(xdrproc_t) xdr_nlm_lockargs, (caddr_t) argp,
		(xdrproc_t) xdr_nlm_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

void *
nlm_free_all_3(nlm_notify *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLM_FREE_ALL,
		(xdrproc_t) xdr_nlm_notify, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

void *
nlmproc4_null_4(void *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLMPROC4_NULL,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

nlm4_testres *
nlmproc4_test_4(nlm4_testargs *argp, CLIENT *clnt)
{
	static nlm4_testres clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLMPROC4_TEST,
		(xdrproc_t) xdr_nlm4_testargs, (caddr_t) argp,
		(xdrproc_t) xdr_nlm4_testres, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

nlm4_res *
nlmproc4_lock_4(nlm4_lockargs *argp, CLIENT *clnt)
{
	static nlm4_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLMPROC4_LOCK,
		(xdrproc_t) xdr_nlm4_lockargs, (caddr_t) argp,
		(xdrproc_t) xdr_nlm4_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

nlm4_res *
nlmproc4_cancel_4(nlm4_cancargs *argp, CLIENT *clnt)
{
	static nlm4_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLMPROC4_CANCEL,
		(xdrproc_t) xdr_nlm4_cancargs, (caddr_t) argp,
		(xdrproc_t) xdr_nlm4_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

nlm4_res *
nlmproc4_unlock_4(nlm4_unlockargs *argp, CLIENT *clnt)
{
	static nlm4_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLMPROC4_UNLOCK,
		(xdrproc_t) xdr_nlm4_unlockargs, (caddr_t) argp,
		(xdrproc_t) xdr_nlm4_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

nlm4_res *
nlmproc4_granted_4(nlm4_testargs *argp, CLIENT *clnt)
{
	static nlm4_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLMPROC4_GRANTED,
		(xdrproc_t) xdr_nlm4_testargs, (caddr_t) argp,
		(xdrproc_t) xdr_nlm4_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

void *
nlmproc4_test_msg_4(nlm4_testargs *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLMPROC4_TEST_MSG,
		(xdrproc_t) xdr_nlm4_testargs, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

void *
nlmproc4_lock_msg_4(nlm4_lockargs *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLMPROC4_LOCK_MSG,
		(xdrproc_t) xdr_nlm4_lockargs, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

void *
nlmproc4_cancel_msg_4(nlm4_cancargs *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLMPROC4_CANCEL_MSG,
		(xdrproc_t) xdr_nlm4_cancargs, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

void *
nlmproc4_unlock_msg_4(nlm4_unlockargs *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLMPROC4_UNLOCK_MSG,
		(xdrproc_t) xdr_nlm4_unlockargs, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

void *
nlmproc4_granted_msg_4(nlm4_testargs *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLMPROC4_GRANTED_MSG,
		(xdrproc_t) xdr_nlm4_testargs, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

void *
nlmproc4_test_res_4(nlm4_testres *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLMPROC4_TEST_RES,
		(xdrproc_t) xdr_nlm4_testres, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

void *
nlmproc4_lock_res_4(nlm4_res *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLMPROC4_LOCK_RES,
		(xdrproc_t) xdr_nlm4_res, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

void *
nlmproc4_cancel_res_4(nlm4_res *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLMPROC4_CANCEL_RES,
		(xdrproc_t) xdr_nlm4_res, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

void *
nlmproc4_unlock_res_4(nlm4_res *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLMPROC4_UNLOCK_RES,
		(xdrproc_t) xdr_nlm4_res, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

void *
nlmproc4_granted_res_4(nlm4_res *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLMPROC4_GRANTED_RES,
		(xdrproc_t) xdr_nlm4_res, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

nlm4_shareres *
nlmproc4_share_4(nlm4_shareargs *argp, CLIENT *clnt)
{
	static nlm4_shareres clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLMPROC4_SHARE,
		(xdrproc_t) xdr_nlm4_shareargs, (caddr_t) argp,
		(xdrproc_t) xdr_nlm4_shareres, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

nlm4_shareres *
nlmproc4_unshare_4(nlm4_shareargs *argp, CLIENT *clnt)
{
	static nlm4_shareres clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLMPROC4_UNSHARE,
		(xdrproc_t) xdr_nlm4_shareargs, (caddr_t) argp,
		(xdrproc_t) xdr_nlm4_shareres, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

nlm4_res *
nlmproc4_nm_lock_4(nlm4_lockargs *argp, CLIENT *clnt)
{
	static nlm4_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLMPROC4_NM_LOCK,
		(xdrproc_t) xdr_nlm4_lockargs, (caddr_t) argp,
		(xdrproc_t) xdr_nlm4_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

void *
nlmproc4_free_all_4(nlm4_notify *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, NLMPROC4_FREE_ALL,
		(xdrproc_t) xdr_nlm4_notify, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}
