# BSDI Makefile,v 1.6 1996/08/27 02:42:11 sanders Exp

PROG=	h2ph
MAN1=	h2ph.0
SRCS=
STRIP=

.include "../../Makefile.inc" 

depend tags:

h2ph: h2ph.pl
	cp ${.CURDIR}/h2ph.pl ./h2ph

.include <bsd.prog.mk>
