#	BSDI Makefile,v 1.1 1998/11/02 16:36:33 jch Exp
#	@(#)Makefile	8.1 (Berkeley) 6/4/93

LIB=	atm
NOSTATIC=
NODYNAMIC=
NOPROFILE=
SRCS=	atm_addr.c cache_key.c ioctl_subr.c ip_addr.c ip_checksum.c \
	md5c.c timer.c

install:

.include <bsd.lib.mk>
