#	BSDI	Makefile,v 2.5 1998/03/09 22:53:54 polk Exp
#	@(#)Makefile	8.2 (Berkeley) 3/31/94

# broken: ching
SUBDIR=	adventure arithmetic atc backgammon battlestar bcd caesar \
	canfield cribbage dm factor fish fortune gomoku hack hangman \
	hunt larn morse number phantasia pig pom ppt primes quiz \
	rain random robots rogue snake trek wargames worm worms \
	wump 

.include <bsd.subdir.mk>
