#	BSDI	Makefile,v 1.24 2002/01/06 22:35:11 polk Exp

SUBDIR=	aicasm ancontrol cpu cytty efsetup ioport iopro kanal msconfig \
	n2setup ncrasm siconfig stlload stlstats tesetup trbsetup \
	wicontrol 

.include <bsd.subdir.mk>
