#	BSDI Makefile,v 2.2 2003/07/08 21:56:07 polk Exp

.include "../Makefile.defs"

PROG=	tfmtodit
SRCS=   tfmtodit.cc
LDADD+=	${LIBGROFF} ${LIBM}
DPADD+=	${LIBGROFF} ${LIBM}

.include "../Makefile.common"
.include <bsd.prog.mk>
