#	BSDI Makefile,v 2.3 2000/03/08 22:28:36 polk Exp

SUBDIR= libbib libdriver libgroff addftinfo afmtodit eqn devX100 \
	devX100-12 devX75 devX75-12 devascii devdvi devlatin1 devlj4 devps \
	grodvi groff grog grohtml grolj4 grops grotty hpftodit indxbib lkbib \
	lookbib man mm nroff pfbtops pic psbb refer soelim tbl tfmtodit \
	tmac troff

.include <bsd.subdir.mk>
