#	BSDI Makefile,v 1.2 1998/12/15 21:24:12 polk Exp

PROG=	atmarpd
MAN8=	atmarpd.0
SRCS=	atmarp_config.c atmarp_log.c atmarp_scsp.c atmarp_subr.c
SRCS+=	atmarp_timer.c atmarpd.c

.include <bsd.prog.mk>
