.TH MSTAT 8 "21 April 1995"
.SH NAME
mstat \- show MBone status
.SH SYNOPSIS
.B mstat
[
.B \-CGIPbdgirtvn
] [
.B \-c
.I community
] [
.B \-p
.I port
] [
.B \-x
.I prefix
] [
.I host
]
.SH DESCRIPTION
.IX  "mstat command"  ""  "\fLmstat\fP \(em display MBone status"
.IX  "MBone status, display \(em \fLmstat\fP"
.IX  "status of MBone, display"  ""  "status of MBone, display \(em \fLmstat\fR"
.LP
.B mstat
displays the contents of various MBone-related data structures
in various formats, depending on the options you select.
.LP
The default value for the
.I host
argument is the localhost.
.SH OPTIONS
.TP 15
.B \-C
Show the cached IP multicast route table for active sources.  This works 
for all types of routers, not just 
.B mrouted .  
The
.B \-x
option can be used to specify a group address.
(This is the default table.)
.TP
.B \-G
Show the PIM group table.
.TP
.B \-I
Show the PIM interface table.
.TP
.B \-P
Show the PIM neighbor table.
.TP
.B \-b
Show the scoped boundary table.  The
.B \-x
option can be used to limit the report to a specific interface number.
.TP
.B \-d
Show the DVMRP neighbor table.  The
.B \-x
option can be used to limit the report to a specific interface number.
.TP
.B \-g
Show the IGMP group table.
.TP
.B \-i
Show the DVMRP interface table.  This is similar to a 
.B mrinfo
report.  The
.B \-x
option can be used to limit the report to a specific (virtual) interface 
number.
.TP
.B \-r
Show the DVMRP routing table.  This is similar to a portion of the 
.B mrouted.dump
file which can be generated by sending a signal to 
.B mrouted .  
The
.B \-x
option can be used to limit the report to a specific subnet address.
.TP
.B \-t
Show the DVMRP routing next hop table.  This is similar to the second
portion of the 
.B mrouted.dump
file.  The
.B \-x
option can be used to limit the report to a specific subnet address.
.TP
.B \-v
Show statistics corresponding to the DVMRP interface table.  The 
.B \-x
option can be used to limit the report to a specific (virtual) interface number.
.TP
.B \-n
Show network addresses as numbers.
.B mstat
normally displays addresses as
symbols.  This option may be used with any of the display formats.
.TP
.BI \-c " community"
Use the specified SNMP community instead of
.B public .
.TP
.BI \-p " port"
Use the specified port to contact
.B snmpd
on the remote host.  The default is the standard SNMP port, 161.
.TP
.BI \-x " prefix"
This use of this option is specific to the table being displayed.  It
is used to limit the range of rows to the subset of the entire table
which corresponds to the given prefix, which may be an integer or
a number IP address, depending on the table.
.SH DISPLAYS
.SS "IP Multicast Route Table"
.LP
The display for each route table entry shows the multicast group and source
addresses, the (virtual) interface on which packets arrive, the number of 
seconds until the entry times out, the received packet and byte counts, the 
number of RPF fails, and the protocol.  A sample use and output might be:
.PP
.nf
.ft C
% mstat sydney.eecs.umich.edu
IP Multicast Route Table for sydney.eecs.umich.edu
Mcast-group   Origin-Subnet   InIf UpTime Tmr   Pkts    Bytes RpF Proto
NTP.MCAST.NET 128.4.1.1/32      1     156 375      1       96   0 dvmrp
NTP.MCAST.NET 128.232.0.56/32   1     466  74      1       96   0 dvmrp
IETF-2-AUDIO. 128.119.40.58/32  1     463  30      1       46   0 dvmrp
224.1.1.94    138.96.24.77/32   1    1665  21    312    38376   0 dvmrp
224.2.0.1     13.2.117.114/32   1     166 180      1       59   0 dvmrp
224.2.0.1     16.1.0.24/32      1     340 210      1       58   0 dvmrp
 ...
.fi.PP
.SS "PIM Group Table"
.LP
The display for each group shows the multicast group address, the mode
(dense or sparse), number of rendezvous points (RPs), and the number of
seconds until this router will send RP-reachable messages.  If the
host does not use PIM, the table will be empty.  A sample use 
and output might be:
.PP
.nf
.ft C
% mstat -G maingate.princeton.edu
PIM Group Table for maingate.Princeton.EDU
Group-Address     Mode   RPs Tmr
NTP.MCAST.NET     dense    0   0
IETF-2-AUDIO.MCAS dense    0   0
SUN-RPC.MCAST.NET dense    0   0
224.1.1.94        dense    0   0
224.2.0.1         dense    0   0
 ...
.fi
.PP
.SS "PIM Interface Table"
.LP
The display for each PIM interface shows the interface number, 
local IP address, mode (dense or sparse), the designated router
for the interface, and the frequency in seconds of router-query
messages.  A sample use and output might be:
.PP
.nf
.ft C
% mstat -I maingate.princeton.edu
PIM Interface Table for maingate.Princeton.EDU
If Address            Mode   DRouter         Ttl Int
 3 128.112.120/22     dense  128.112.120.1     0  30
 4 128.112.224/22     dense  128.112.224.1     0  30
 6 128.112.200/22     dense  128.112.200.200   0  30
 7 128.112.232/22     dense  128.112.232.1     0  30
 9 maingate.Princeton dense  0.0.0.0          64  30
.fi
.PP
.SS "PIM Neighbor Table"
.LP
The display for each PIM neighbor shows the interface number, seconds 
since the router (last) became a neighbor,
seconds until this entry times out, active PIM mode (dense or sparse)
of the neighbor, and the neighbor address.  A sample use and output might be:
.PP
.nf
.ft C
% mstat -P maingate.princeton.edu
PIM Neighbor Table for maingate.Princeton.EDU
If UpTime ExpTm Mode   Neighbor
 6      0    85 dense  csgate.Princeton.EDU
.fi
.PP
.SS "Boundary Table"
.LP
The display for each scoped boundary shows the (virtual) interface number and 
administratively scoped boundary address.  A sample use and output might be:
.PP
.nf
.ft C
% mstat -b sydney.eecs.umich.edu
Boundary Table for sydney.eecs.umich.edu
Vif Boundary Address
  1 239.2/16          
.fi
.PP
.SS "DVMRP Neighbor Table"
.LP
The display shows the (virtual) interface number, seconds
since the router (last) became a neighbor, seconds left before
timing out, the generation ID and version number of the neighbor, and
the neighbor address.
A sample use and output might be:
.PP
.nf
.ft C
% mstat -d sydney.eecs.umich.edu
DVMRP Neighbor Table for sydney.eecs.umich.edu
Vif UpTime ExpTm     GenId Version Neighbor
 1    1637   136 796725035 3.3     videosrv2.engin.umich.edu
.fi
.PP
.SS "IGMP Group Table"
.LP
The display shows the multicast group address, the interface
number, whether the local system is a member of the group address on
that interface, the number of seconds since this row was created, the 
number of seconds left until it expires, and the last system reporting 
itself a member.  A sample use and output might be:
.PP
.nf
.ft C
% mstat -g sydney.eecs.umich.edu
IGMP Group Table for sydney.eecs.umich.edu
Group-Address   Vif Self   UpTime Tmr Member
224.2.127.255    0  true     1498 164 sydney.eecs.umich.edu
224.2.212.225    0  false    1503 177 grinch.eecs.umich.edu
.fi
.PP
.SS "DVMRP Virtual Interface Table"
.LP
The display shows the (virtual) interface number, local and remote addresses 
of the interface, the metric and threshold, and the type and current state.
A sample use and output might be:
.PP
.nf
.ft C
% mstat -i sydney.eecs.umich.edu
DVMRP Virtual Interface Table for sydney.eecs.umich.edu
Vif Local-Address   Met Thr Type    State Remote-Address
 0  141.212.99.117    1   1 querier up    141.212.98/23
 1  141.212.99.117    1   1 tunnel  up    videosrv2.engin.umich.edu
 2  141.212.99.117    1   1 tunnel  down  conn1054-classroom1.engin.umich.edu
.fi
.PP
.SS "DVMRP Route Table"
.LP
The display shows the origin, incoming Vif, distance to origin, seconds 
until timeout, and upstream neighbor.  A sample use and output might be:
.PP
.nf
.ft C
% mstat -r sydney.eecs.umich.edu
DVMRP Route Table for sydney.eecs.umich.edu
Origin-Subnet      IVif Met Tmr  UpstreamNeighbor
13.0.32/22            1  11 173  videosrv2.engin.umich.edu
13.1.100/22           1   9 173  videosrv2.engin.umich.edu
13.1.108/22           1  10 173  videosrv2.engin.umich.edu
13.1.136/22           1  10 173  videosrv2.engin.umich.edu
 ...
.fi
.PP
.SS "DVMRP Route Next Hop Table"
.LP
The display shows the origin, outgoing (virtual) interface, and state (leaf
or branch).  If status is leaf, then a multicast datagram from that 
origin will be forwarded on that outgoing vif only if there are members 
of the destination group on that leaf.  A sample use and output might be:
.PP
.nf
.ft C
% mstat -t sydney.eecs.umich.edu
DVMRP Route Next Hop Table for sydney.eecs.umich.edu
Origin-Subnet      OVif State
13.0.32/22            0 leaf
13.0.32/22            2 leaf
13.1.100/22           0 leaf
13.1.100/22           2 leaf
13.1.108/22           0 leaf
13.1.108/22           2 leaf
 ...
.fi
.PP
.SS "DVMRP Virtual Interface Statistics Table"
.LP
The display shows the (virtual) interface number, remote address, 
incoming and outgoing packet and byte counts, the rate limit, and
the interface type and current state.  A sample use and output 
might be:
.PP
.nf
.ft C
% mstat -v sydney.eecs.umich.edu
DVMRP Virtual Interface Statistics Table for sydney.eecs.umich.edu
Vif  InPkts OutPkts    InBytes   OutBytes Rate Type    State Remote-Address
 0       64   18335      16165   18441723    0 querier up    141.212.98/23     
 1    18817      64   18472738      16165  500 tunnel  up    videosrv2.engin.um
 2        0       0          0          0  500 tunnel  down  conn1054-classroom
.fi
.PP
.SH "SEE ALSO"
.BR netstat (8C),
.BR mtrace (8),
.BR mrouted (8)
