#
# Makefile.ov,v 1.1.1.1 2003/08/14 15:53:19 polk Exp
#

TOP = .
include $(TOP)/config.mk/template

SUBDIRS = ../lib/kadm5 server create passwd import export v4server \
	keytab cli testing dbutil

expand SubdirTarget
