# Make `routed` tools for BSD/OS
# 1.1
# $FreeBSD: src/sbin/routed/rtquery/Makefile,v 1.7.2.1 2001/04/25 10:58:50 ru Exp $

PROG=	rtquery
SRCS=	rtquery.c md5c.c
MAN8=	rtquery.0
#LDADD+=	-lmd
#DPADD+=	${LIBMD}
#COPTS=	-g -DDEBUG -W -Wall -Wcast-align -Wcast-qual -Winline -Wpointer-arith -Wnested-externs -Wwrite-strings -Wunused

.PATH: ${.CURDIR}/..

.include <bsd.prog.mk>
