#	BSDI Makefile,v 2.2 2003/07/08 21:56:05 polk Exp

.include "../Makefile.defs"

PROG=	addftinfo
SRCS=   addftinfo.cc guess.cc
LDADD+=	${LIBGROFF}
DPADD+=	${LIBGROFF}

.include "../Makefile.common"
.include <bsd.prog.mk>
