.\"	BSDI vreset.1,v 2.1 1995/02/03 13:32:19 polk Exp
.Dd January 3, 1994
.Dt VRESET 1
.Os
.Sh NAME
.Nm vreset
.Nd reset VGA display to text-mode
.Sh SYNOPSIS
.Nm vreset
.Sh DESCRIPTION
.Nm Vreset
is used to reset VGA display adaptors to text-mode.  While it should
seldom be necessary, 
.Nm vreset
can sometimes save a reboot when another program (e.g., 
.Xr X 1 )
leaves the display in an unknown or otherwise unusable state.
.Sh SEE ALSO
.Xr vgafont 1 ,
.Xr pccons 4
.Sh HISTORY
The
.Nm vreset
command is
.Ud .
