# Makefile.ov,v 1.1.1.1 2003/08/14 15:53:24 polk Exp

TOP = ../..
include $(TOP)/config.mk/template

GEN_SCRIPTS = compare_dump.pl fixup-conf-files.pl make-host-keytab.pl \
	simple_dump.pl verify_xrunner_report.pl

all:: $(GEN_SCRIPTS) restore_files.sh

restore_files.sh:
	ln -s save_files.sh restore_files.sh

%.pl: %.pl.in
	-rm -f $@.tmp
	echo "#!$(PERL)" > $@.tmp
	sed 1d $@.in >> $@.tmp
	chmod +x $@.tmp
	mv $@.tmp $@

clean::
	-rm -f $(GEN_SCRIPTS) *.tmp
