#	BSDI Makefile,v 2.1 1995/02/03 12:38:44 polk Exp

.include "../Makefile.defs"

PROG=	pfbtops
SRCS=	pfbtops.c
LDADD+=	${LIBGROFF}
DPADD+=	${LIBGROFF}

.include "../Makefile.common"
.include <bsd.prog.mk>
