#       BSDI Makefile,v 2.1 1995/02/03 13:16:35 polk Exp

LIB=            args
SRCS=           Args.c ArgsUsage.c DoArgs.c
NOPROFILE=      noprofile

# The library is not installed
install:

.include <bsd.lib.mk>
.include <bsd.man.mk>
