#	BSDI Makefile,v 1.3 1998/12/15 21:24:11 polk Exp

PROG=	atm
SRCS=	atm.c atm_fore200.c atm_eni.c atm_inet.c atm_print.c
SRCS+=	atm_set.c atm_show.c atm_subr.c
MAN8=	atm.0

#LFLAGS+=-i

.include <bsd.prog.mk>
