#!/bin/sh

# Copyright (c) 1999-2001 Sendmail, Inc. and its suppliers.
#	All rights reserved.
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the sendmail distribution.
#
#
#	Build,v 1.3 2003/09/17 21:19:21 polk Exp

exec sh ../devtools/bin/Build $*
