#	BSDI Makefile,v 1.2 2003/07/08 21:56:06 polk Exp

.include "../Makefile.defs"

PROG=	hpftodit
SRCS=	hpftodit.cc
LDADD+=	${LIBGROFF} ${LIBM}
DPADD+=	${LIBGROFF} ${LIBM}

.include "../Makefile.common"
.include <bsd.prog.mk>
