.\" Copyright (c) 1996 Berkeley Software Design, Inc. All rights reserved.
.\" The Berkeley Software Design Inc. software License Agreement specifies
.\" the terms and conditions for redistribution.
.\"
.\"	BSDI tokenadm.8,v 1.3 1996/09/06 00:44:07 prb Exp
.Dd August 23, 1996
.Dt TOKENADM 8
.Os BSD/OS
.Sh NAME
.Nm activadm , cryptoadm , snkadm
.Nd manage the ActivCard, CRYPTOCard and SNK-004 token databases
.Sh SYNOPSIS
.Nm tokenadm
.Op Fl 1BDERT
.Op Fl d
.Op Fl e
.Op Fl m Ar [-]mode
.Op Fl r
.Op Ar user Op ...
.Sh DESCRIPTION
The
.Nm tokenadm
utility is display and edit user entries in the various token databases.
It may also be invoked as one the following:
.Nm activadm , cryptoadm ,
or
.Nm snkadm .
The flags available are:
.Bl -tag -width indent
.It Fl 1
Display users, one per line.
.It Fl B
Display users with no banner.
.It Fl D
Display disabled users.
.It Fl E
Display enabled users.
.It Fl R
Display users in reverse order.
.It Fl T
Display users in terse format (only the user names).
Unless
.Fl 1
is also specified, four users will be displayed per line.
.It Fl d
Disable users without removing them from the database.
This prevents the users from authenticating, but does not loose their
shared secret.
The
.Fl m
flag may also be used with the
.Fl d
flag.
.It Fl e
Enable users.
This should be used to re-enable users who were disabled by the
.Fl m
flag may also be used with the
.Fl e
flag
option.
.It Fl m
Add
[or remove]
the specified mode of authentication for the user.  Modes available are
decimal (dec), hexadecimal (hex) and phonebook (phone) and reduced-input (rim).
Not all modes are available for all types of cards.
The
.Fl m
flag may be used alone or in conjunction with either the
.Fl de
flags.
When ever reduced-input mode is set the reduced-input state is reset.
This should be done if a paper copy of challenge/responses had been
produced and then misplaced.
.It Fl r
Remove users from the database.
.El
.sp
Use of any of the
.Fl 1BDERT
flags precludes the use of any of the
.Fl demr
flags.
The
.Fl demr
flags all require at least one
.Ar user
argument.
.Sh SEE ALSO
.Xr x99token 1 ,
.Xr login.conf 5 ,
.Xr login_token 8 ,
.Xr tokeninit 8 ,
