#	BSDI Makefile,v 1.1.1.1 2001/12/19 02:11:06 donn Exp

PROG=	ldconfig
CFLAGS+=-g -W -Wall -Wshadow -Wpointer-arith -Wstrict-prototypes \
	-Wmissing-prototypes
MAN8=	ldconfig.0

.include <bsd.prog.mk>
