#	BSDI Makefile,v 2.2 2003/07/08 21:56:07 polk Exp

.include "../Makefile.defs"

PROG=	tbl
SRCS=   main.cc table.cc
LDADD+=	${LIBGROFF}
DPADD+=	${LIBGROFF}

.include "../Makefile.common"
.include <bsd.prog.mk>
