# WILDBOAR $Wildboar: Makefile,v 1.4 1996/03/17 08:31:54 shigeya Exp $

LIB=	cs
SRCS=	Open.c Close.c GetMaxSlot.c GetCIS.c GetSlotFlags.c \
	SetSlotFlags.c GetClientInfo.c GetLastAttach.c
CFLAGS+=-I/sys
NOMAN=	noman
NOPROFILE=noprofile

.include <bsd.lib.mk>
