/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_SZTYPES_H_RPCGEN
#define	_RPC_SZTYPES_H_RPCGEN

#include <rpc/rpc.h>

#ifdef __cplusplus
extern "C" {
#endif

#pragma ident	"@(#)rpc_sztypes.x	1.2	93/07/09 SMI"

typedef u_int64_t uint64;

typedef int64_t int64;

typedef u_long uint32;

typedef long int32;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_uint64(XDR *, uint64*);
extern  bool_t xdr_int64(XDR *, int64*);
extern  bool_t xdr_uint32(XDR *, uint32*);
extern  bool_t xdr_int32(XDR *, int32*);

#else /* K&R C */
extern bool_t xdr_uint64();
extern bool_t xdr_int64();
extern bool_t xdr_uint32();
extern bool_t xdr_int32();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_SZTYPES_H_RPCGEN */
