.\" Copyright (c) 1996, 1998 Berkeley Software Design, Inc.
.\" All rights reserved.
.\" The Berkeley Software Design Inc. software License Agreement specifies
.\" the terms and conditions for redistribution.
.\"
.\"	BSDI config_X.8,v 1.2 1998/06/03 00:42:19 donn Exp
.\"
.Dd May 30, 1998
.Os
.Dt CONFIG_X 8
.Sh NAME
.Nm config_X
.Nd "configure the X server environment"
.Sh SYNOPSIS
.Nm config_X
.br
.Sh DESCRIPTION
The
.Nm config_X
program helps the user configure the X Window System server
using a trial and error scheme.
.\" It attempts to auto-detect mice and talks the user through configuring
.\" other parts of the system in a trial-and-error type scheme.
.Sh SEE ALSO
.Xr X 1 ,
.Xr XFree86 1
.Sh HISTORY
The 
.Nm config_X
command first appeared in BSD/OS and is currently under development.
