#	BSDI Makefile,v 2.2 1995/12/06 18:10:38 polk Exp

LIB=	rcs
SRCS=   maketime.c partime.c rcsedit.c rcsfcmp.c rcsfnms.c rcsgen.c \
	rcskeep.c rcskeys.c rcslex.c rcsmap.c rcsrev.c rcssyn.c \
	rcstime.c rcsutil.c version.c

NOMAN=	noman
NOPROFILE=noprofile

install:

.include <bsd.lib.mk>
