#!/bin/sh
#	BSDI	archie,v 1.1 1998/11/20 23:01:18 tks Exp

ARCHIE=/usr/contrib/bin/archie


echo Content-type: text/html
echo

if [ -x $ARCHIE ]; then
	if [ $# = 0 ]; then
		cat << EOM
<TITLE>Archie Gateway</TITLE>
<H1>Archie Gateway</H1>

<ISINDEX>

This is a gateway to archie. Type search query in your browser's search 
dialog.<P>
EOM
	else
		echo \<PRE\>
		$ARCHIE "$*"
	fi
else
	echo Cannot find archie on this system.
fi

