.\" Copyright (c) 1992 Berkeley Software Design, Inc
.\" All rights reserved.
.\"
.\"
.\"	@(#)fdformat.1	1.0 (BSDI) 02/09/92
.\"
.Dd Feb 9, 1992
.Dt FDFORMAT 1
.Os BSD 4
.Sh NAME
.Nm fdformat
.Nd format floppy disk
.Sh SYNOPSIS
.Nm fdformat
.Op Fl lv
.Ar device
.Op Ar disk_type
.Sh DESCRIPTION
The
.Nm fdformat
utility formats floppy disks.
.Pp
The following options are available:
.Bl -tag -width flag
.It Fl l
Place a disk label on the disk after formatting.
.It Fl v
Provide verbose output,
including printing the track and head number during formatting.
.El
.Pp
The
.Ar device
argument is the name of the floppy disk's device special file
(normally in the
.Pa /dev
directory).
If
.Ar device
does not begin with a slash, the prefix
.Pa /dev/
is prepended to the name.
If the resulting file does not exist,
an
.Dq a
is appended to the name.
.Pp
The
.Ar disk_type
argument is the name of a disk description entry in
.Pa /etc/disktab .
The conventional names are
.Dq Li floppy
for 1.44MB HD 3.5 disks,
and
.Dq Li floppy15
for 1.2MB HD 5.25 disks.
If not specified,
.Ar disk_type
defaults to
.Dq Li floppy .
.Pp
Floppies which are to be used as BSD/OS filesystems need to be
formatted with 
.Nm fdformat ,
labeled with
.Xr disksetup 8
(or by specifying the
.Fl l
option) and then a filesystem should be created on the floppy using
.Xr newfs 8 .
.Pp
The
.Nm fdformat
utility exits 0 on success, and >0 if an error occurs.
.Sh SEE ALSO
.Xr floppy 4 ,
.Xr disktab 5 ,
.Xr disksetup 8 ,
.Xr newfs 8
.Sh HISTORY
The
.Nm fdformat
command first appeared in
BSDI.
