#	BSDI	Makefile,v 1.1 2001/05/09 15:11:14 seebs Exp
#	@(#)Makefile	8.1 (Berkeley) 6/5/93

MAN6=	intro.0

all: ${MAN6}

clean depend lint tags:

cleandir:
	rm -f ${MAN6}

install: maninstall

.include <bsd.prog.mk>
