.\"
.\" Copyright (c) 1993 Berkeley Software Design, Inc. All rights reserved.
.\" The Berkeley Software Design Inc. software License Agreement specifies
.\" the terms and conditions for redistribution.
.\"
.\"	@(#) BSDI accton.8,v 2.1 1995/02/03 17:07:02 polk Exp
.\"
.Dd January 25, 1993
.Dt ACCTON 8
.Os
.Sh NAME
.Nm accton
.Nd enable/disable system accounting
.Sh SYNOPSIS
.Nm accton
.Op Ar file
.Sh DESCRIPTION
With no argument,
.Nm accton
will disable system accounting.  If the argument is an existing pathname,
record collection is enabled and for every process initiated which terminates
under normal conditions an accounting record is appended to
.Ar file .
.Sh SEE ALSO
.Xr acct 2 ,
.Xr acct 5 ,
.Xr sa 8
.Sh HISTORY
A
.Nm accton
command appeared in Version 7 AT&T UNIX.
