#	BSDI Makefile,v 2.1 1995/02/03 12:37:55 polk Exp

.include "../Makefile.defs"

MAN5=	groff_font.0 groff_out.0
MAN7=	groff_char.0

tags depend:

install: maninstall

.include "../Makefile.common"
.include <bsd.prog.mk>
