.\" Copyright (c) 1999 Berkeley Software Design, Inc.
.\" All rights reserved.
.\" The Berkeley Software Design Inc. software License Agreement specifies
.\" the terms and conditions for redistribution.
.\"	BSDI randomd.8,v 1.2 2000/01/12 23:04:32 polk Exp
.Dd September 18, 1999
.Dt RANDOMD 8
.Sh NAME
.Nm randomd
.Nd generate random numbers
.Sh SYNOPSIS
.Nm randomd
.Op Fl ctv
.Op Fl f Ar conf-file
.Sh DESCRIPTION
.Pp
The
.Nm randomd
daemon opens sockets and accepts requests for random numbers on one or
more local domain sockets.
The options available are:
.Bl -tag -width indent
.It Fl c
Force use of the system cycle counter.  This is currently only supported
on Pentimum processors, or better.
.It Fl f
Use
.Ar conf-file
instead of the default
.Pa /etc/random.conf
configuration file.
.It Fl t
Force use of the system clock (tick).
.It Fl v
Produce some verbose output and do not run as a daemon.
.El
.Pp
When started, the
.Nm randomd
daemon puts itself in the background and detaches itself
from the controlling tty,
unless
.Fl v
was specified.
It runs at a nice level of 15 to prevent it from
competing with normal processes on the system.
.Sh ALGORITHM
The current algorithm used by
.Nm randomd
is to either read the time of day approximately 60 times a second,
using the
.Li tv_usec
field to obtain 3 bits of random data,
or by reading the system cycle counter approximately 100 times a second
to obtain 3 bits of random data.
Once 32 bits have been collected they are stored in a circular queue
of 4096 numbers.
When requested to produce a random number, the daemon takes the next two
unused numbers out of the queue.
If all current numbers in the queue have been consumed, the DES or MD5
algorithm is optionally used to cyclically encrypt a random 64 bit seed.  Only
the upper 32 bits of the result are returned.
The key used to do the cyclical encryption is taken from the physically
first two 32 bit random numbers in the circular queue.  This implies the
DES key changes approximately every 11.8 minutes.
The seed which is cyclically encrypted is updated each time a new set of 32
random bits is generated by the standard generator above.  The new bits
are alternately placed in the upper and lower 32 bits of the seed.  This
implies the seed is modified approximately 6 times a second.
.Sh CONFIGURATION
If the default configuration file
.Pa /etc/random.conf
is not present and
.Ar conf-file
is not specified, the default configuration is:
.Bd -literal -offset indent
/var/run/random
/var/run/random.ascii ascii
/var/run/random.stream stream
/var/run/random.string stream ascii md5
/var/run/random.des stream des
/var/run/random.md5 stream md5
.Ed
.sp
Each line in the configuration specifies a file name and a set of options,
separated by spaces.
The file name specifies the name of the local domain socket that will
service random number requests.  The options specify how those random
numbers will be provided.
The options are:
.sp
.Bl -tag -width indent -offset indent
.It ascii
Provide the random numbers in hexadecimal ascii digits.
.It des
If no random numbers are ready, use DES to generate a new random number.
.It md5
If no random numbers are ready, use MD5 to generate a new random number.
.It stream
Normally a single 64 bit result is made available.  The stream option
produces as much data as requested by the client.  This is normally
combined with either
.Nm des
or
.Nm md5 .
.El
.sp
If neither
.Nm des
nor
.Nm md5
are specified then only numbers generated by the clock are used.
.Sh BUGS
This generator has not been cryptographically examined.
It is relatively uniform and spans the entire 64 bit space.
Different processor speeds may effect the randomness of the data.
.Sh COPYRIGHT
Copyright (c) 1995,1996,1999 Paul R. Borman <prb@krystal.com> 
.br
All rights reserved.
.sp
Permission to use, copy, and modify this software without fee
is hereby granted, provided that this entire notice is included in
all copies of any software which is or includes a copy or
modification of this software and in all copies of the supporting
documentation for such software.
.sp
THIS SOFTWARE IS BEING PROVIDED "AS IS", WITHOUT ANY EXPRESS OR IMPLIED
WARRANTY.  IN PARTICULAR, THE AUTHOR MAKES NO REPRESENTATION OR WARRANTY
OF ANY KIND CONCERNING THE MERCHANTABILITY OF THIS SOFTWARE OR ITS FITNESS
FOR ANY PARTICULAR PURPOSE.
.sp
The 
.Nm md5
algorithm is properly known as the
.%B "RSA Data Security, Inc. MD5 Message-Digest Algorithm"
and is
.Bd -literal -offset indent
Copyright (C) 1991-2, RSA Data Security, Inc. Created 1991.
All rights reserved.
.Ed
