#	@(#)Makefile	8.7 (Berkeley) 8/18/96

DIR=usd/11.vitut
SRCS=ex.cmd.roff merge.awk set.opt.roff spell.ok vi.cmd.roff vi.ref

all:
	${MAKE} -f Makefile

clean:
	${MAKE} -f Makefile clean

cleandir:	clean

.include <bsd.doc.mk>