#	BSDI Makefile,v 1.1 1998/08/28 12:11:30 torek Exp

# man pages are installed from w.v8
PROG=	w.v9
MAN1=
.PATH: ${.CURDIR}/../w
CFLAGS+=-DSPARCV9
LINKS=	${BINDIR}/w.v9 ${BINDIR}/uptime.v9

.include "../w/Makefile"
