#	BSDI Makefile.inc,v 2.2 1995/10/10 02:33:37 donn Exp
#
#	@(#)Makefile.inc	8.1 (Berkeley) 6/4/93

SRCS+=	bcmp.s bcopy.s bzero.s ffs.s index.s memchr.s memcmp.s \
	memcpy.s memmove.s memset.s rindex.s strcat.s strchr.s \
	strcmp.s strcpy.s strcspn.c strlen.s strncat.s strncmp.s \
	strncpy.s strpbrk.c strrchr.s strsep.c strspn.c strstr.c
