/* This file is automatically generated.
   It defines a symbol `__stub_FUNCTION' for each function
   in the C library which is a stub, meaning it will fail
   every time called, usually setting errno to ENOSYS.  */
#define __stub___ieee754_j0l
#define __stub___ieee754_j1l
#define __stub___ieee754_jnl
#define __stub___ieee754_lgammal_r
#define __stub___ieee754_rem_pio2l
#define __stub___ieee754_y0l
#define __stub___ieee754_y1l
#define __stub___ieee754_ynl
#define __stub___kernel_cosl
#define __stub___kernel_rem_pio2l
#define __stub___kernel_sinl
#define __stub___kernel_tanl
#define __stub_chflags
#define __stub_erfcl
#define __stub_erfl
#define __stub_fchflags
#define __stub_fexecve
#define __stub_gtty
#define __stub_lchown
#define __stub_madvise
#define __stub_revoke
#define __stub_setlogin
#define __stub_sigaltstack
#define __stub_sigstack
#define __stub_sstk
#define __stub_stty
