#	BSDI Makefile,v 1.3 2002/01/18 21:06:33 polk Exp

LIB=	kvm
TARGET=	kvmv9

# For compatible changes, increment minor
# For incompatible changes use increment major
LDDYNMAJOR=.0
LDDYNMINOR=.0

.include "../libkvm.sparc/Makefile"
