#	BSDI Makefile,v 2.2 2003/07/08 21:56:06 polk Exp

.include "../Makefile.defs"

PROG=	soelim
SRCS=   soelim.cc
LDADD+=	${LIBGROFF}
DPADD+=	${LIBGROFF}

.include "../Makefile.common"
.include <bsd.prog.mk>
