#	BSDI	Makefile,v 1.2 2002/07/11 17:59:29 seebs Exp
#	@(#)Makefile	8.1 (Berkeley) 6/5/93

MAN8=boot.0
MANSUBDIR=/powerpc

all: ${MAN8}

clean depend lint tags:

cleandir:
	rm -f ${MAN8}

install: maninstall

.include <bsd.prog.mk>
