#	BSDI Makefile,v 1.2 2003/07/08 21:56:05 polk Exp

.include "../Makefile.defs"

PROG=	grolj4
SRCS=   lj4.cc
LDADD+=	${LIBDRIVER} ${LIBGROFF} ${LIBM}
DPADD+=	${LIBDRIVER} ${LIBGROFF} ${LIBM}

.include "../Makefile.common"
.include <bsd.prog.mk>
