.\"
.\" Copyright (c) 1996 Berkeley Software Design, Inc. All rights reserved.
.\" The Berkeley Software Design Inc. software License Agreement specifies
.\" the terms and conditions for redistribution.
.\"
.\" BSDI pthread_cleanup.3,v 1.3 1996/12/12 03:03:41 donn Exp
.\" 
.Dd June 3, 1996
.Dt PTHREAD_CLEANUP 3
.Os BSD 4
.Sh NAME
.Nm pthread_cleanup_push ,
.Nm pthread_cleanup_pop
.Nd thread specific data value functions
.Sh SYNOPSIS
.Fd #include <pthread.h>
.Ft void
.Fn pthread_cleanup_push "void (*routine)(void *)" "void *arg"
.Ft void 
.Fn pthread_cleanup_pop "int execute"
.Sh DESCRIPTION
.Pp
This interface is defined by
.St -p1003.1c .
.Pp
The
.Fn pthread_cleanup_push
function pushes the pthread_exit cleanup handler specified by
.Fa routine 
on the calling thread's cleanup handler stack.  This handler is
popped from the stack and executed with the single argument specified in 
.Fa arg
when the given thread calls 
.Fn pthread_exit 
or exits its start routine, or when
.Fn pthread_cleanup_pop
is called with
.Fa execute
set non-zero.
.Pp
The 
.Fn pthread_cleanup_pop
function removes the topmost element from the calling thread's cleanup 
stack and optionally executes it if 
.Fa execute 
is passed non-zero.  The popped cleanup routine is called with the 
argument registered when
.Fn pthread_cleanup_push
was called.
.Sh SEE ALSO
.Xr pthreads 3 ,
.Xr pthread_exit 3
.Sh STANDARDS
The
.Nm pthread_cleanup_push
and
.Nm pthread_cleanup_pop
functions conform to
.St -p1003.1c .
.Sh HISTORY
The
.Nm pthread_cleanup_push
and
.Nm pthread_cleanup_pop
functions first appeared in BSD/OS 3.0.
.Sh BUGS
Pthread cleanup handlers are also intended for use with
.Fn pthread_cancel ,
which this implementation does not currently support.
