/*-
 * Copyright (c) 1996 Berkeley Software Design, Inc. All rights reserved.
 * The Berkeley Software Design Inc. software License Agreement specifies
 * the terms and conditions for redistribution.
 *
 *      BSDI thread_trace.c,v 1.6 2000/08/24 15:03:10 jch Exp
 */

/*
 *	Wraparound thread trace buffer.
 *
 *	To enable tracing globally add '-DKTR' to the +CFLAGS definition in
 * 	the Makefile.inc in this directory.
 *
 *	This tracing is intended to be lightweight enough to run in a
 *	production environment (if need be). It is used much like
 *	printf, however for each trace call (actually inline via a
 *	macro) only a trace entry (5 words) is updated (the time, a
 *	pointer to the printf style string, and two parameter words).
 *
 *  Usage:
 *    Unconditional traces:
 *	TR(fmt, p1, p2)		- Simple trace entry
 *
 *  Notes:
 *	'fmt' is a pointer to a character string, usually generated by the
 *	compiler (as in "xxxx"). Only the pointer is stored, if the string
 *	is not constant then the result when the buffer is formatted may
 *	not be what is expected.
 *
 *	'p1' and 'p2' may be any small (4 bytes or less) data type, they
 *	are cast into an unsigned long.
 *
 *	The trace buffer can be inspected by hand with gdb, by using the
 *	tdump script for gdb, or by running the tdump program (this is the
 *	preferred method).
 */

/* Requires sys/types.h and sys/time.h */

#include <sys/types.h>
#include <sys/time.h>

struct pttr_entry {
	struct	timeval pttr_tv;
	char	*pttr_desc;
	u_long	pttr_parm1;
	u_long	pttr_parm2;
};

#ifdef KTR
#define	PTTR_SIZE	16*1024
struct pttr_entry pttr_buf[PTTR_SIZE];
int pttr_idx = 0;
int pttr_size = PTTR_SIZE;
int pttr_size_mask = PTTR_SIZE - 1;
int pttr_elemsize = sizeof(struct pttr_entry);
#ifdef DEBUG
int (*_thread_death)() = NULL;
#endif

void
_thread_trace(char *desc, unsigned parm1, unsigned parm2)
{
	struct pttr_entry *k;
	int sec, usec;
	int scratch;
	int i;

	/* Atomically get a trace buffer slot.  */
	asm (
		"   movl %3,%1\n"
		"   addl $1,%1\n"
		"   andl %4,%1\n"
		"   movl %3,%0\n"
		"   movl %1,%2\n"
		"   leal (%0,%0,4),%0\n"
		"   leal pttr_buf(,%0,4),%0"
		:
		"=&a" (k), "=&r" (scratch), "=m" (pttr_idx) :
		"2" (pttr_idx), "i" (PTTR_SIZE - 1));

	k->pttr_desc = desc;
	k->pttr_parm1 = parm1;
	k->pttr_parm2 = parm2;
	
	/* Sample the Pentium timer.  */
	asm (".byte   0x0f, 0x31" : "=a" (usec), "=d" (sec));
	k->pttr_tv.tv_usec = usec;
	k->pttr_tv.tv_sec = sec;
}

#endif
