#	@(#)Makefile	8.7 (Berkeley) 8/18/96

DIR=usd/13.viref
SRCS=vi.ref index.so *.roff *.awk spell.ok

all:
	${MAKE} -f Makefile

clean:
	${MAKE} -f Makefile clean

cleandir:	clean

.include <bsd.doc.mk>