SUBDIR+=bgpd faithd gifconfig hroute6d icmp6dump ifmcstat ip6addrctl mld6query \
	ndp pim6dd pim6sd prefix racoon route6d rrenumd \
	rtsold rtadvd rip6query setkey scope6config
#SUBDIR+=dtcp inet6d racoon

.include <bsd.subdir.mk>
