#	BSDI Makefile,v 2.2 1996/09/25 04:06:54 donn Exp
#
#	@(#)Makefile	8.1 (Berkeley) 6/6/93

PROG=	ld
SRCS=	ld.c cplus-dem.c

CFLAGS+=	-DSTANDARD_SEARCH_DIRS="\"/usr/lib\", \"/usr/contrib/lib\", \"/usr/local/lib\""

.include <bsd.prog.mk>
