#	BSDI Makefile,v 2.1 1995/02/03 12:36:10 polk Exp

.include "../Makefile.defs"

LIB=	bib
SRCS=	common.cc index.cc linear.cc map.c search.cc
NOPROFILE=noprofile
NOMAN=	noman

install:

.include "../Makefile.common"
.include <bsd.lib.mk>

.SUFFIXES: .cc
