.\" Copyright (c) 1996 Berkeley Software Design, Inc. All rights reserved.
.\" The Berkeley Software Design Inc. software License Agreement specifies
.\" the terms and conditions for redistribution.
.\"
.\"	BSDI login_chpass.8,v 1.2 1997/01/15 20:50:13 bostic Exp
.Dd August 1, 1996
.Dt LOGIN_CHPASS 8
.Os BSD/OS
.Sh NAME
.Nm login_chpass
.Nd change password authentication type
.Sh SYNOPSIS
.Nm login_chpass
.Op Fl s Ar service
.Ar user
.Op Ar class
.Sh DESCRIPTION
.Pp
The
.Nm
utility is typically called from
.Xr login 8 .
It is functionally the same as calling the program:
.Dq passwd Ar user .
This will change the users kerberos password, if configured,
or use the
.Xr login_lchpass 8
utility to change the users local password.
Only the
.Li login
service is supported.
See
.Xr login.conf 5 .
The
.Ar class
argument is not used.
.Sh SEE ALSO
.Xr passwd 1 ,
.Xr login.conf 5 ,
.Xr login 8 ,
.Xr login_lchpass 8
