.\" WILDBOAR $Wildboar: apmstart.8,v 1.3 1996/02/13 13:00:59 shigeya Exp $
.\" 
.\" Portions or all of this file are Copyright(c) 1994,1995,1996
.\" Yoichi Shinoda, Yoshitaka Tokugawa, WIDE Project, Wildboar Project
.\" and Foretune.  All rights reserved.
.\"
.\" This code has been contributed to Berkeley Software Design, Inc.
.\" by the Wildboar Project and its contributors.
.\"
.\" The Berkeley Software Design Inc. software License Agreement specifies
.\" the terms and conditions for redistribution.
.\"     
.\" THIS SOFTWARE IS PROVIDED BY THE WILDBOAR PROJECT AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
.\" FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE
.\" WILDBOAR PROJECT OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
.\" GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
.\" WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
.\" NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
.\" SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd June 15, 1995
.Dt APMSTART 8
.Os
.Sh NAME
.Nm apmstart
.Nd enable APM kernel support code
.Sh SYNOPSIS
.Nm apmstart
.Op Fl q
.Sh DESCRIPTION
The
.Nm apmstart
command enables APM (Advanced Power Management) on machines
which support it.
.Pp
The following options are available:
.Bl -tag -width indent
.It Fl q
The
.Fl q
option causes
.Nm apmstart
to not complain if APM is unavailable.
.Sh SEE ALSO
.Xr apmstop 8
.Sh AUTHOR
Yoichi Shinoda <shinoda@jaist.ac.jp>
