#	BSDI Makefile,v 2.3 1995/10/17 20:10:54 bostic Exp
# from Id: Makefile,v 1.3 1993/03/10 23:10:06 dlu Rel

PROG=    msconfig
CFLAGS+= -DHZ=100 -DMSDEBUG -DMSDIAG -I/sys
MAN8=    msconfig.0

.include <bsd.prog.mk>
