#	BSDI Makefile.inc,v 1.2 2002/01/09 16:07:59 donn Exp

SRCS+=  bcmp.c bcopy.s bzero.s ffs.s index.c memchr.s memcmp.c \
	memcpy.s memmove.s memset.s rindex.c strcat.c strcmp.c \
	strcpy.c strcspn.c strlen.s strncat.c strncmp.c strncpy.c \
	strpbrk.c strsep.c strspn.c strstr.c
