#	BSDI Makefile,v 2.4 2002/06/20 16:03:14 seebs Exp
#
#	@(#)Makefile	8.1 (Berkeley) 6/5/93

# SUBDIR no longer includes bsdi, the old config.n and driver.n are no
# longer supported
SUBDIR=	cyclades equinox psd smm usd 

all depend lint tags mansourceinstall:

.include <bsd.subdir.mk>
